### PR TITLE
Thenextweb

### PR DESCRIPTION
**Pull request by sabayounis**
All is done

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
Hi Team, 👋👋
🙂 🙂  You have done an amazing job on the project. 🙂🙂  
 I  am impressed, but there are a few additions to make.

- #### **[REQUIRED]** README 🙂 
Your readme file is supposed to be descriptive enough(readme has to describe the project you have worked on in detail. It can include information on collaborators, the technology used, why the project was designed, how to access, etc... ).[readme](https://github.com/Forison/Using-Bootstrap)

- ### **[REQUIRED]** HTML🙂
You should fix the errors given to you by the[ validator ](https://validator.w3.org)when uploading the index file.🙂

- ### **[OPTIONAL]** HTML🙂
> It would be better to make the navbar fixed at the top
# Kindly make those changes and submit for review again
🙂🙂Happy coding🙂🙂

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: almost done. However, small changes needs to be made in order to get approval for this project. check below :arrow_down: 

- Your fixed navbar is getting transparent when you scroll down the page. :pray:  fix it (using z-index)
- You still have some linter errors to fix :worried:

###  That's it :relaxed: . When finished, kindly resubmit another code review request :pray:

**Review by whiz25 — APPROVED** [review]
## Bravo :clap: team
You have met all the requirements and, therefore, this project is complete. Please merge and continue with the next projects.

**Pull request merged**
